apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep-aiops.gatewayName" . }}
  labels:
    {{- include "keep-aiops.labels" . | nindent 4 }}
    {{- include "keep-aiops.gatewaySelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8090
      targetPort: http
  selector:
    {{- include "keep-aiops.gatewaySelectorLabels" . | nindent 4 }}
