apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep-aiops.apiName" . }}
  labels:
    {{- include "keep-aiops.labels" . | nindent 4 }}
    {{- include "keep-aiops.apiSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "keep-aiops.apiSelectorLabels" . | nindent 4 }}
